##########Biz Config##########
#####Tms Api Config#####
#api address
tms_api_host: tmsuat.yudianbank.com
tms_api_port: 8887
tms_api_path: /tms
app_api_host: bj.app.yudianbank.com
app_api_port: 8080
app_api_path: /app
#token
tms_api_token: eyJlbmNyeXB0ZWREYXRhIjoiMjdlT3p4MlNOaUxJdlJ6WjJ0YjBhc3g3MXExL1craCsyc0ZwcERxSWVHYndsNUpDMEJkQnlIeTdoQnlYenhXMndCQ1RCT2pMcFJiWHhlbDNQTkxJUWl2eUFVR0dJVXZRNGxxM2FyWXZDOWpvRWkyK1h6cmFtQ0l1SXhYZWMzS1kxY2V0Nm56WDYrbVBnV2dCOWZEL0FqWUN5QUNkeFRLWC9hT1d4czZBWFhjQjZvZ3NFNithWi9kdjZLMDZ2M0tOTmRwMmd4dm5zRTFkM1dtK1ZNOHpRUWtGblBHTXJSQjlvVXcyS0FGRU1LWnp4ZWRHclNaeFE2NE0vNWNSVG1mY3cyYjdyekw4TkpQVWQ1VmgydFljd1I4eExpMTFCWXFRc3cwVGVzYW9yME09Iiwid3JhcHBlZEtleSI6ImRoY3l3YXVUTmd1Q3BNQjlZY2gvZkxURU8xVzdVT2VTeC9JWFRyUEN1bmFNWUpsSTBCNlZlM01TZjlvTmFORHBRM3NOR2EzejhwNTBUalp2QnArMEh3PT0ifQ==
tms_api_YD_OAUTH: eyJlbmNyeXB0ZWREYXRhIjoiMjdlT3p4MlNOaUxJdlJ6WjJ0YjBhc3g3MXExL1craCsyc0ZwcERxSWVHYndsNUpDMEJkQnlIeTdoQnlYenhXMndCQ1RCT2pMcFJiWHhlbDNQTkxJUWl2eUFVR0dJVXZRNGxxM2FyWXZDOWpvRWkyK1h6cmFtQ0l1SXhYZWMzS1kxY2V0Nm56WDYrbVBnV2dCOWZEL0FqWUN5QUNkeFRLWC9hT1d4czZBWFhjQjZvZ3NFNithWi9kdjZLMDZ2M0tOTmRwMmd4dm5zRTFkM1dtK1ZNOHpRUWtGblBHTXJSQjlvVXcyS0FGRU1LWnp4ZWRHclNaeFE2NE0vNWNSVG1mY3cyYjdyekw4TkpQVWQ1VmgydFljd1I4eExpMTFCWXFRc3cwVGVzYW9yME09Iiwid3JhcHBlZEtleSI6ImRoY3l3YXVUTmd1Q3BNQjlZY2gvZkxURU8xVzdVT2VTeC9JWFRyUEN1bmFNWUpsSTBCNlZlM01TZjlvTmFORHBRM3NOR2EzejhwNTBUalp2QnArMEh3PT0ifQ==
partnerNo: wanshui
#已认证外请车
mobile_certificate: ['13077327043','18301771383','15000422980']


##########log Config##########
log_path_info: /home/testing/Logs/tms_uat
log_path_error: /home/testing/Logs/tms_uat/error

##########Mail Config##########
#receiver eg:['eamilAddress1@keking.cn','eamilAddress2@keking.cn']
email_receiver : [ 'liuxinyu@keking.cn']
#sender
email_sender : 'ahkj@keking.cn'
email_sender_pwd : 'redmineonly'
#mail server
email_host : mail.keking.cn
#mail title prefix
email_title : "TMS迭代BVT测试报告"

#########DB Config###########
db_host: 106.75.31.207
db_port: 23306
db_user: yd_devp
db_passwd: yd_7758
db_dbname: YDAPPDB
db_charset: utf8