##########Biz Config##########
#####Tms Api Config#####
#api address
tms_api_host: tmsuat.yudianbank.com
tms_api_port: 8887
tms_api_path: /tms
app_api_host: bj.app.yudianbank.com
app_api_port: 8080
app_api_path: /app
#token
tms_api_token: eyJlbmNyeXB0ZWREYXRhIjoiTDhGTlRWUFhpa21pb1Zqak9ZQ2FLeWNnTXF6ZzdwR2xsRWlQOGdpbWttZFRXSFliMFZxOG5aVmhScHF0VnhJY3B2K2Z5bk8xVWlWdEh4V0E0TE4ycThKNjB4M0dxQVRUOVlLNno2Z1pxdWtXMGlub0RhbVl0THcvb0IxUEIvbGNoc1l3d2RNL3YvclB6RXVCQThqVFF2UTNkaEoxNUI2ZkRyOTJHc3RWNmxuYlNsNzdreTltbzJiOWVxS2FITDNVVWE3UHlIZU1XNXdtZFljWDVDdjlKcFFxMlIyY0UxUVFWdzJKZjJpMmRORUdWenJ5MlRjRURxakhCZG15cGk5WkVKZjdNU0krR2d1cWxRaXNmakRubFN6TE9hUDVPMURhREFwOE9aZkQ2QzA9Iiwid3JhcHBlZEtleSI6IkVPeGJmT2gxdzhmbE1qazJXTFJUNlRseVZQU3J0Sy8xaU41cHBTNVQ0YnVpbWMybnZsaFB3YWJmZGpMMWZnOG5oWlhiMTRvRjY3YkUzTThKNEk1bjZBPT0ifQ==
tms_api_YD_OAUTH: eyJlbmNyeXB0ZWREYXRhIjoiTDhGTlRWUFhpa21pb1Zqak9ZQ2FLeWNnTXF6ZzdwR2xsRWlQOGdpbWttZFRXSFliMFZxOG5aVmhScHF0VnhJY3B2K2Z5bk8xVWlWdEh4V0E0TE4ycThKNjB4M0dxQVRUOVlLNno2Z1pxdWtXMGlub0RhbVl0THcvb0IxUEIvbGNoc1l3d2RNL3YvclB6RXVCQThqVFF2UTNkaEoxNUI2ZkRyOTJHc3RWNmxuYlNsNzdreTltbzJiOWVxS2FITDNVVWE3UHlIZU1XNXdtZFljWDVDdjlKcFFxMlIyY0UxUVFWdzJKZjJpMmRORUdWenJ5MlRjRURxakhCZG15cGk5WkVKZjdNU0krR2d1cWxRaXNmakRubFN6TE9hUDVPMURhREFwOE9aZkQ2QzA9Iiwid3JhcHBlZEtleSI6IkVPeGJmT2gxdzhmbE1qazJXTFJUNlRseVZQU3J0Sy8xaU41cHBTNVQ0YnVpbWMybnZsaFB3YWJmZGpMMWZnOG5oWlhiMTRvRjY3YkUzTThKNEk1bjZBPT0ifQ==
partnerNo: wanshui

#已认证外请车
mobile_certificate: ['13077327043','18301771383','15000422980']


##########log Config##########
log_path_info: /home/testing/Logs/tms_uat
log_path_error: /home/testing/Logs/tms_uat/error

##########Mail Config##########
#receiver eg:['eamilAddress1@keking.cn','eamilAddress2@keking.cn']
email_receiver : ['zhangdawei@keking.cn', 'liuxinyu@keking.cn', 'panyuanyuan@keking.cn', 'qihong@keking.cn',
                    'tangyanhu@keking.cn','luozhoukai@keking.cn','zhaojiapeng@keking.cn']
#sender
email_sender : 'ahkj@keking.cn'
email_sender_pwd : 'redmineonly'
#mail server
email_host : mail.keking.cn
#mail title prefix
email_title : "TMS迭代BVT测试报告"

#########DB Config###########
db_host: 106.75.31.207
db_port: 23306
db_user: kk_hf
db_passwd: kk$3763
db_dbname: YDAPPDB1
db_charset: utf8